"""add secure transfers

Revision ID: 1022bd6ce795
Revises: c402103d47fd
Create Date: 2026-06-02 03:52:54.379947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1022bd6ce795'
down_revision: Union[str, None] = 'c402103d47fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secure_transfers',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('salt', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('sender_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_email', sa.String(length=320), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('has_password', sa.Boolean(), nullable=False),
    sa.Column('one_time', sa.Boolean(), nullable=False),
    sa.Column('max_downloads', sa.BigInteger(), nullable=False),
    sa.Column('download_count', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_consumed', sa.Boolean(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secure_transfers_token_hash'), 'secure_transfers', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_secure_transfers_token_hash'), table_name='secure_transfers')
    op.drop_table('secure_transfers')
    # ### end Alembic commands ###
