"""Read-only SharePoint intelligence and private user connections."""
from alembic import op
import sqlalchemy as sa

revision = "i4d5e6f7a8b9"
down_revision = "h3c4d5e6f7a8"
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sharepoint_sources',
    sa.Column('scope_key', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('site_id', sa.String(length=255), nullable=False),
    sa.Column('drive_id', sa.String(length=255), nullable=False),
    sa.Column('folder_id', sa.String(length=255), nullable=False),
    sa.Column('policy', sa.String(length=16), nullable=False),
    sa.Column('rules_cipher', sa.Text(), nullable=True),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('delta_link', sa.Text(), nullable=True),
    sa.Column('next_link', sa.Text(), nullable=True),
    sa.Column('generation', sa.String(length=36), nullable=True),
    sa.Column('active_run_id', sa.String(length=36), nullable=True),
    sa.Column('lease_owner', sa.String(length=36), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_key')
    )
    op.create_table('sharepoint_connections',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('token_cipher', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('sharepoint_documents',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('web_url', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('modified_at', sa.String(length=64), nullable=True),
    sa.Column('is_folder', sa.Boolean(), nullable=False),
    sa.Column('in_scope', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('seen_generation', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('segments', sa.JSON(), nullable=True),
    sa.Column('mapping_cipher', sa.Text(), nullable=True),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('usage', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('approval_hash', sa.String(length=64), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sharepoint_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'item_id', name='uq_sharepoint_source_item')
    )
    op.create_index(op.f('ix_sharepoint_documents_source_id'), 'sharepoint_documents', ['source_id'], unique=False)
    op.create_index(op.f('ix_sharepoint_documents_status'), 'sharepoint_documents', ['status'], unique=False)
    op.create_table('sharepoint_runs',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('discovered', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sharepoint_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sharepoint_runs_source_id'), 'sharepoint_runs', ['source_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sharepoint_runs_source_id'), table_name='sharepoint_runs')
    op.drop_table('sharepoint_runs')
    op.drop_index(op.f('ix_sharepoint_documents_status'), table_name='sharepoint_documents')
    op.drop_index(op.f('ix_sharepoint_documents_source_id'), table_name='sharepoint_documents')
    op.drop_table('sharepoint_documents')
    op.drop_table('sharepoint_connections')
    op.drop_table('sharepoint_sources')
    # ### end Alembic commands ###
